### ISSUE TITLE
Is repo URL & the project dead now?

### ISSUE THREAD

**Issue by nanoant** [archmac/packages#13]
Hi @lloeki,

Is the project dead. It looks like repository server is no longer working:
~~~
:: Synchronizing package databases...
 manual is up to date
error: failed retrieving file 'core.db' from archmac.fra1.cdn.digitaloceanspaces.com : The requested URL returned error: 400
error: failed to update core (unexpected error)
error: failed retrieving file 'extra.db' from archmac.fra1.cdn.digitaloceanspaces.com : The requested URL returned error: 400
error: failed to update extra (unexpected error)
error: failed to synchronize all databases
~~~

If you no longer want to finance this project, maybe a Patreon page would help?
Regards,
-- Adam

**Comment by lloeki** [comment]
Hey, see [this post](https://lna7n.org/2020/01/06/pulling-the-plug-on-archmac.html).

Some people asked for me to put up stuff again. Time is as much a problem as money and I did not have time to look into GH Sponsors or Patreon legalities details.

I'll try to find a moment to spin that data back up.

**Comment by nanoant** [comment]
> Hey, see this post.

Many fair points. I completely understand your decision.

> Some people asked for me to put up stuff again. Time is as much a problem as money(...)

Yeah. Some say time is a money. Btw. anyone there was willing to take over?

**Comment by lloeki** [comment]
I managed to have the repos and snapshots up again.
